export class User {
  constructor(
    public readonly id: string,
    public readonly role: string,
    public readonly status: string,
    public readonly username: string,
    public readonly email: string,
    public readonly emailVerificationToken: string | null,
    public readonly emailVerificationTokenExpiresAt: Date | null,
    public readonly emailFailedVerificationAttempts: number,
    public readonly hashedPassword: string,
    public readonly failedLoginAttempts: number,
    public readonly passwordResetToken: string | null,
    public readonly passwordResetTokenExpiresAt: Date | null,
    public readonly passwordResetFailedVerificationAttempts: number,
    public readonly passwordUpdatedAt: Date | null,
    public readonly lockedUntil: Date | null,
    public readonly multiFactorEnabled: boolean,
    public readonly recoveryEmail: string | null,
    public readonly recoveryEmailVerificationToken: string | null,
    public readonly recoveryEmailVerificationTokenExpiresAt: Date | null,
    public readonly recoveryEmailFailedVerificationAttempts: number,
    public readonly phoneNumber: string | null,
    public readonly phoneNumberVerificationToken: string | null,
    public readonly phoneNumberVerificationTokenExpiresAt: Date | null,
    public readonly phoneNumberFailedVerificationAttempts: number,
    public readonly isNewsletterAllowed: boolean,
    public readonly termsAcceptedAt: Date,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public readonly isEmailVerified: boolean,
    public readonly isRecoveryEmailVerified: boolean,
    public readonly isPhoneNumberVerified: boolean
  ) {}

  static create(
    id: string,
    role: string,
    status: string,
    username: string,
    email: string,
    emailVerificationToken: string | null,
    emailVerificationTokenExpiresAt: Date | null,
    emailFailedVerificationAttempts: number,
    hashedPassword: string,
    failedLoginAttempts: number,
    passwordResetToken: string | null,
    passwordResetTokenExpiresAt: Date | null,
    passwordResetFailedVerificationAttempts: number,
    passwordUpdatedAt: Date | null,
    lockedUntil: Date | null,
    multiFactorEnabled: boolean,
    recoveryEmail: string | null,
    recoveryEmailVerificationToken: string | null,
    recoveryEmailVerificationTokenExpiresAt: Date | null,
    recoveryEmailFailedVerificationAttempts: number,
    phoneNumber: string | null,
    phoneNumberVerificationToken: string | null,
    phoneNumberVerificationTokenExpiresAt: Date | null,
    phoneNumberFailedVerificationAttempts: number,
    isNewsletterAllowed: boolean,
    termsAcceptedAt: Date,
    createdAt: Date,
    updatedAt: Date,
    isEmailVerified: boolean,
    isRecoveryEmailVerified: boolean,
    isPhoneNumberVerified: boolean
  ): User {
    return {
      id,
      role,
      status,
      username,
      email,
      emailVerificationToken,
      emailVerificationTokenExpiresAt,
      emailFailedVerificationAttempts,
      hashedPassword,
      failedLoginAttempts,
      passwordResetToken,
      passwordResetTokenExpiresAt,
      passwordResetFailedVerificationAttempts,
      passwordUpdatedAt,
      lockedUntil,
      multiFactorEnabled,
      recoveryEmail,
      recoveryEmailVerificationToken,
      recoveryEmailVerificationTokenExpiresAt,
      recoveryEmailFailedVerificationAttempts,
      phoneNumber,
      phoneNumberVerificationToken,
      phoneNumberVerificationTokenExpiresAt,
      phoneNumberFailedVerificationAttempts,
      isNewsletterAllowed,
      termsAcceptedAt,
      createdAt,
      updatedAt,
      isEmailVerified,
      isRecoveryEmailVerified,
      isPhoneNumberVerified,
    };
  }
}
